### ISSUE TITLE
Table view support for RDF result formats

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#101]
The table is currently only used to display the SPARQL result formats.

`construct` and `describe` queries return RDF results, which can be displayed in an SPO or SPOG table.

**Comment by LaurensRietveld** [comment]
I'm inclined not to add an RDF results parser, as we won't be able to find one that covers all serialization formats. And: we do support rendering of construct queries, when the accept header is set to tsv or csv

**Comment by wouterbeek** [comment]
@LaurensRietveld You're right, in 2017 we do not have a web-based RDF parsing library that covers (at least) the currently standardized formats.  Luckily the Semantic Web mailing list has been hammering away on the important question of how to represent the Cartesian adage "I am" in RDF for the last week, so it is understandable that they have not found the time to build a web-based parser with broad coverage yet.
