### ISSUE TITLE
Disable mouse wheel scrolling over the map view

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#102]
When YASR is embedding within a larger page, a user who wants to scroll the page often inadvertently scrolls the map view.

**Comment by LaurensRietveld** [comment]
This should be possible, but lets wait for leaflet to fix this issue first: https://github.com/Leaflet/Leaflet/issues/5310

**Comment by wouterbeek** [comment]
To clarify my OP: this should be an option the programmer can set.  In some circumstances you want the map to scroll, in other circumstances you do not want this at all.

These may indeed be Leaflet options that already exist or are under development.  In that case this issue would already be solved by a bit of documentation on how to configure Leaflet.

**Comment by LaurensRietveld** [comment]
I'm using this approach now in one lib: https://gis.stackexchange.com/a/210712
It's relatively intuitive: clicking on a map enables scrolling. Clicking outside the map disables it. 
A couple of downsides:
- There is no user feedback that the user should click the item before being able to scroll
- Haven't tested this on mobile yet

**Comment by LaurensRietveld** [comment]
Added an option `YASR.plugins.leaflet.defaults.clickBeforeInteract` (disable by default) that has the above behaviour
