### ISSUE TITLE
in dist/yasr.js relative-require of lib/DataTables/media/js/jquery.dataTables.js will not resolve

### ISSUE THREAD

**Issue by esjewett** [Triply-Dev/YASGUI.YASR-deprecated#11]
Just upgraded to the latest version of YASR. Thanks for doing the bundle thing here as well!

At the moment we'll need to use the yasr.bundled.min.js as yasr.min.js has a relative require of "lib/DataTables/media/js/jquery.dataTables.js" included in it. Should this either be shimmed or included in the bundle?

**Comment by LaurensRietveld** [comment]
Shimming should not be required, as this plugin attaches itself to the jquery instance.
I've added an example file (see index-deps.html). Let me know if you still experience issues

gr Laurens

**Comment by esjewett** [comment]
Ah, right. So if we just include the dataTables plugin prior to loading YASR, it won't try to do the relative require? Makes sense. I will give that a shot. Thanks.

**Comment by LaurensRietveld** [comment]
Jup, it feels a bit fragile though (but it works ;))
