### ISSUE TITLE
Add support for JSON-LD result sets

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#110]
For `construct` and `describe` queries allow the result format 'JSON-LD' to be set in the settings pane.

Apply syntax coloring to the obtained JSON-LD reply body (preferably JSON-LD-specific coloring, and otherwise generic JSON-coloring).

**Comment by LaurensRietveld** [comment]
Continuing here https://github.com/TriplyDB/Yasgui/issues/135
