### ISSUE TITLE
Make "yasr_header" easy to hide

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#119]
I've recently implemented an enduser-facing list ([Articles by Kim Wall](http://zbw.eu/beta/sparql-lab/wd_results.html?endpoint=https://query.wikidata.org/bigdata/namespace/wdq/sparql&queryRef=https://api.github.com/repos/zbw/sparql-queries/contents/wikidata/articles_by.rq&author=wd:Q36519983&pageTitle=Articles+by+Kim+Wall&hide=1), linked from the German and English Wikipedia). For that, I found no easy way to hide the yasr_header line completely. (If it exists already, please let me know.)

**Comment by GerwinBosch** [comment]
You can hide the yasr_header by adding the snippet below to your CSS
```css
.yasr_header {
  display: none;
}
```

Let me know if that fixed it for you

**Comment by jneubert** [comment]
Yes, that would fix it, but that would not allow for my cgi argument "hide=1" (or: don't hide) to work. Would it perhaps be possible to add id="yasr_header" (or similar) to the according div?

**Comment by LaurensRietveld** [comment]
Hi Joachim, not sure what you mean. I dont want to set any id's here, as that would create issues when running multiple yasgui instances on one page.

**Comment by jneubert** [comment]
Hi Laurens, in my js I have a these lines:
```javascript
    if (args.hide && args.hide === "1") {
      document.getElementById("yasqe").style.display = "none";
      YASR.defaults.drawOutputSelector = false;
    }
```
to switch the display off for all page elements not necessary for end-user, which can be left out e.g. for debugging.

I understand your rationale against an id when multiple instances on one page should work. So I have to iterate over all elements with class="yasr_header"?

**Comment by GerwinBosch** [comment]
There should only be one instance of the yasr_header class within Yasgui, so
```js
document.getElementsByClassName("yasr_header")[0].style.display = "none";
```
Should work.


Or, If you have multiple instances running and want to only hide the header of the mentioned one above
```js
document.getElementById("yasqe").getElementsByClassName("yasr_header")[0].style.display = "none";
```
should work

**Comment by jneubert** [comment]
Well, I had tried that, but it hadn't worked before - as it turned out, because I've called it before the yasr structure had been build. When I put the line behind the execution of yasqe.query, it works smoothly. 

Sorry for my poor knowledge of javascript.
