### ISSUE TITLE
Get Clicked data(row) / event

### ISSUE THREAD

**Issue by nicky508** [Triply-Dev/YASGUI.YASR-deprecated#121]
Hi,

For own of our applications we load sparql results to YASR and visualize these results. However we would like to add some interaction in this visualizations. GChart has features to do this, however I am struggling to get this done via YASR. As a start I try to get the value (or the datarow) after I click on it in the table or bar chart for example. Is this possible and how should I achieve this?

**Comment by semanticfire** [comment]
A simple solution would be to enable the option to add a handler to the configuration object, tricky part however is that the handlers from google charts are lacking parameters, you'll need to address the chart object yourself. This could be solved by adding parameters to the YASR handler internally.

I'll code some ideas in a fork and do a PR
