### ISSUE TITLE
Buttons default to submit when places in html form

### ISSUE THREAD

**Issue by semanticfire** [Triply-Dev/YASGUI.YASR-deprecated#123]
All buttons on the YASR interface lack a 'type' so when YASR is integrated in a <form> the buttons will invoke a submit.
According to HTML specs to prevent this from happening they should have a 'type="button"' attribute.

PR will follow

**Comment by LaurensRietveld** [comment]
This is fixed in the new release (see monorepo https://github.com/TriplyDB/Yasgui)
