### ISSUE TITLE
Be notified when output plugin changes

### ISSUE THREAD

**Issue by tfrancart** [Triply-Dev/YASGUI.YASR-deprecated#125]
Hello

I have a use-case where the SPARQL query being generated will change depending on the type of output selected by the user.

- if the user selects "Geo" a preprocessing of the query will automatically add the necessary criterias and output colums to select the geographic coordinates to be displayed.
- if the user selects "Timeline" (yes, we are working on a timeline plugin, too), the query will be modified to select start and end dates

It seems there is no hook for this this events are emitted once a plugin starts to draw the result.
Can you confirm this analysis ? or how could we regenerate and re-execute a new SPARQL query everytime the user selects a different output plugin ?

Would it be possible to add an extra event to be notified when a user has selected an output plugin ?

**Comment by LaurensRietveld** [comment]
Event handling was indeed an issue in the previous version of Yasr. In the new version (see Yasgui monorepo at https://github.com/TriplyDB/Yasgui ) we've improved event handling. There is now a `draw` and a `drawn` event: https://github.com/TriplyDB/Yasgui/blob/master/packages/yasr/src/index.ts#L25

If you're still having issues with this use-case, please file an issue here: https://github.com/TriplyDB/Yasgui/issues
