### ISSUE TITLE
Timeline plugin

### ISSUE THREAD

**Issue by tfrancart** [Triply-Dev/YASGUI.YASR-deprecated#126]
We are working on a plugin to display the results in a timeline using http://visjs.org/docs/timeline/.
This could be used to display either instant date or period using start/end dates.

**Comment by LaurensRietveld** [comment]
Thanks, interesting. In the meantime we've settled on a different timeline plugin (see https://triplydb.com/wikimedia/dbpedia/queries/timeline-cars/6) but would be curious to see a comparison! 

I'll close this issue for now, as this repository is deprecated. All activities will continue in the Yasgui monorepo at https://github.com/TriplyDB/Yasgui .

**Comment by tfrancart** [comment]
Our timeline plugin using visJS is at https://github.com/sparna-git/humanum-masa/blob/master/explorateur/src/main/webapp/theme-default/js/timeline.js

I think it is quite different in usage than yours using TimelineJS. TimelineJS is more for editorial timelines and requires a picture and a description to display nicely, while VisJS is more of a "raw" timeline and can work without image/description.
