### ISSUE TITLE
Inactive buttons in outputSelector

### ISSUE THREAD

**Issue by tfrancart** [Triply-Dev/YASGUI.YASR-deprecated#129]
Hi !

For some reason, I can't click on the buttons to select the type of output. "Table" is always selected, and I cannot click on the other types of output, even though they are not greyed.

Here is what I did to integrate YASR :

```
<link href='https://cdn.jsdelivr.net/npm/yasgui-yasr@2.12.19/dist/yasr.min.css' rel='stylesheet' type='text/css'/>
...

	<script src="https://cdn.jsdelivr.net/npm/yasgui-yasr@2.12.19/dist/yasr.bundled.min.js"></script>
	<script src="<c:url value="/resources/MDB-Free/js/jquery-3.1.1.min.js" />"></script>
	<script src="<c:url value="/resources/MDB-Free/js/popper.min.js" />"></script>
	<script src="<c:url value="/resources/MDB-Free/js/bootstrap.min.js" />"></script>
```

Any idea what can cause this ? am I doin something wrong ?
Thanks !

**Comment by LaurensRietveld** [comment]
Do you have a minimum working example of your problem? (see https://jsbin.com/dihayuqera/edit?html,js,output for a start)

**Comment by tfrancart** [comment]
Thanks for your reply, trying to have a minimal example of the problem helped me find the problem : some stupid CSS declarations left from previous tests !

```
.select_Timeline, .select_gchart, .select_pivot, .select_rawResponse, .select_table{
	 cursor: not-allowed;
     pointer-events: none;
}
```

So no problem with YASR !
If I may add a followup question : is there a way to control (from Javascript) the output type to display the query results ? we know in some situations that we want to have table/geo/timeline display because we generate the SPARQL query ourselves.

**Comment by LaurensRietveld** [comment]
Good to hear it's solved. About drawing the correct plugin: you could try this on instantiation: `YASR(someElement, {output: 'geo'}, someSparqlResponse)`.

**Comment by tfrancart** [comment]
Actually, I can't get this to work : is seems that the output that was previously selected remains selected. Is there anything to do with persistence, too ?

**Comment by LaurensRietveld** [comment]
You could try setting `persistency` to false in the config

**Comment by tfrancart** [comment]
yep, works with the floowing config ! Thanks

```
yasr = YASR(
  document.getElementById("yasr"),
  { 
    "output": view,
    "persistency": { "prefix": false, "results": { "key": false }}
  },
  response
);
```
