### ISSUE TITLE
(It seems like) parsing of SPARQL XML results does not decode escaped &lt; / &gt;

### ISSUE THREAD

**Issue by tfrancart** [Triply-Dev/YASGUI.YASR-deprecated#130]
Raw response :

![screenshot-raw-response](https://user-images.githubusercontent.com/2728945/49885190-eb0d3300-fe36-11e8-834a-8fb2f381e4ed.png)

Table rendering :

![screenshot-table](https://user-images.githubusercontent.com/2728945/49885199-ed6f8d00-fe36-11e8-977f-b7138e6e12c4.png)

**Comment by tfrancart** [comment]
When getting the results in JSON, the '<' and '>' are displayed properly

**Comment by LaurensRietveld** [comment]
Do you have a mwe? Here, it seems to work fine: http://yasgui.org/short/scfbcZLdQ

**Comment by tfrancart** [comment]
The following query at http://yasgui.org/# is able to reproduce this behavior :

```
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?test WHERE {
  ?s ?p ?o
  BIND(("12 < 18") AS ?test)
} 
LIMIT 10
```

Swith between the "Table" and "Response" output format to compare.

**Comment by LaurensRietveld** [comment]
Thanks, this is now fixed in https://github.com/TriplyDB/Yasgui/commit/a4ad62b704b5383b0bbd4f58c3105fe650ab5e93
