### ISSUE TITLE
CSV download doesn't match standard

### ISSUE THREAD

**Issue by mlesicko** [Triply-Dev/YASGUI.YASR-deprecated#132]
The downloaded CSV results are formatted with spaces around the commas:

```
 "sub" , "pred" , "obj" ,
 "http://www.openlinksw.com/virtrdf-data-formats#default-iid" , "http://www.w3.org/1999/02/22-rdf-syntax-ns#type" , "http://www.openlinksw.com/schemas/virtrdf#QuadMapFormat" ,
```

From [RFC-4180](https://tools.ietf.org/html/rfc4180), "Spaces are considered part of a field and should not be ignored.", and the examples in both that document and [W3C's CSV on the Web](https://www.w3.org/TR/2016/NOTE-tabular-data-primer-20160225) show no spaces around the commas.

These extra spaces cause the downloaded results to display incorrectly when opened in Excel.

**Comment by LaurensRietveld** [comment]
Fixed by #133
