### ISSUE TITLE
Problems importing npm module via webpack in react

### ISSUE THREAD

**Issue by D063520** [Triply-Dev/YASGUI.YASR-deprecated#135]
I'm trying to import the module in a react project. I'm using the standard react-create-app which uses webpack to import the dependencies.

```
import React, {Component, PropTypes} from 'react'
import logo from './logo.svg';
import YASQE from 'yasgui-yasqe';
import YASR from 'yasgui-yasr';
import 'yasgui-yasqe/dist/yasqe.css';
import 'yasgui-yasr/dist/yasr.css';
import './App.css';

export class App extends Component {

    constructor(props) {
        super(props);
    }

    componentDidMount() {
        this.yasqe = YASQE.fromTextArea(document.getElementById('yasqe'), {
            sparql: {
                showQueryButton: true,
                endpoint: "http://localhost:4567/api/endpoint/cocktails/sparql",
            },

        });

        this.yasr = YASR(document.getElementById('yasr'), 
            {   
                outputPlugins: ["error", "boolean", "rawResponse", "table", "pivot", "leaflet"], 
                useGoogleCharts: false,
             });

        this.yasqe.options.sparql.callbacks.complete = this.yasr.setResponse;
    }

    render() {
        return (
            <div>
                <div>
                    <textarea id='yasqe' style={{width: 400}} autosize={{minRows: 10, maxRows: 10}}/>
                    <div id="yasr"></div>
                </div>
            </div>


        )
    }
}
```

Following problems:
1) Module not found: Can't resolve './images/layers-2x.png' in '/Users/MyUser/WebstormProjects/test/node_modules/yasgui-yasr/dist'

I fix this by either adding the corresponding leaflet files in '/Users/MyUser/WebstormProjects/test/node_modules/yasgui-yasr/dist'.

2) ./node_modules/yasgui-yasr/src/gChartLoader.js
Module not found: Can't resolve 'google' in '/Users/Dennis/WebstormProjects/test/node_modules/yasgui-yasr/src'

The problem is the google dependency here. Note that also appears when putting " useGoogleCharts: false,".

I fix this by eliminating the files that define gChart and by commenting the part of code out in main.js and in pivot.js

3) finally the table component fails to be imported. The problem is the following line:

https://github.com/TriplyDB/YASGUI.YASR/blob/480075c291037f0ebfbea8fc12c0c91138a16306/src/table.js#L3

I change:

require("datatables.net")();

to 

require("datatables.net");

Then the module is imported correctly and can be used.

I'm not an expert but I assume these problem arise due to the way webpack is trying to import the npm module. I think fixing this issues makes the library usable via webpack. Note that I do not encounter any issue when importing other npm modules using the default create-react-app setup.

**Comment by danmichaelo** [comment]
Indeed, I ran into it the same problem with a minimal Webpack setup (no React).

```
import YASR from 'yasgui-yasr'
```

gave the following error when running Webpack:

```
ERROR in ./node_modules/yasgui-yasr/src/gChartLoader.js
Module not found: Error: Can't resolve 'google' in '/Users/danmichael/projects/bibsent/skosmos-stack/query_service/node_modules/yasgui-yasr/src'
 @ ./node_modules/yasgui-yasr/src/gChartLoader.js 10:27-44 28:13-30 45:10-27 57:6-23 69:15-32
 @ ./node_modules/yasgui-yasr/src/main.js
 @ ./src/index.js

ERROR in ./node_modules/yasgui-yasr/src/gchart.js
Module not found: Error: Can't resolve 'google' in '/Users/danmichael/projects/bibsent/skosmos-stack/query_service/node_modules/yasgui-yasr/src'
 @ ./node_modules/yasgui-yasr/src/gchart.js 16:17-34 195:11-28 195:33-50
 @ ./node_modules/yasgui-yasr/src/main.js
 @ ./src/index.js
```

Webpack supports normal [CommonJS require()](https://webpack.js.org/api/module-methods/#require) statements, but in this case "google" is not a package, but a global defined through a browserify shim in [package.json](https://github.com/TriplyDB/YASGUI.YASR/blob/gh-pages/package.json#L91-L93)). Which is not something Webpack understands. 

I tried working around this by download the google jsapi:

    curl -o src/google.js https://www.google.com/jsapi

and adding a manual alias in `webpack.config.js`:

```js
module.exports = {
  resolve: {
    alias: {
      'google': path.join(__dirname, 'src/google.js'),
    }
  }
}
```

but it seems like some more webpack magic is needed to make this fully work.. The workaround described above works, but involves editing the source code :/

In the long term, it would probably be good to make use of the [googlecharts npm package](https://www.npmjs.com/package/google-charts) instead. … And right after writing that sentence I noticed that there is a [new yasgui repo](https://github.com/Triply-Dev/Yasgui) in the works, so it seems like @LaurensRietveld & co are already working on modernizing the YASGUI package(s) 🎉

**Comment by LaurensRietveld** [comment]
See https://triply.cc/docs/yasgui-api#react for a snippet on how to include the new yasgui version in react. That snippet uses Yasgui, but using Yasqe and/or Yasr instead would be very similar.

If there are other issues, let me know in the new Yasgui monorepo: https://github.com/TriplyDB/Yasgui
If you have documentation improvements, please submit a PR here: https://github.com/TriplyDB/Documentation/
