### ISSUE TITLE
mergeLabelsWithUris not working for second column?

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#15]
Hi Laurens,

It is absolutely phantastic to see that you put my suggestion #14 in code within just a day! 

However, I couldn't get it to work properly. This may be related somehow to local settings or caching, but even with a restarted browser, cache cleared and code loaded from Github, I get an error: The second uri/label pair is overridden with the label of the first (while the first one is formatted perfectly).

My debugging efforts were not sucessful, so I just send you the URL and a screenshot, in case it looks different for you:

http://zbw.eu/beta/sparql-lab/?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/stw/added_by_category.rq

![1](https://cloud.githubusercontent.com/assets/2128921/5129906/cb982b06-70e6-11e4-8701-24782a2f650e.PNG)

Cheers, Joachim

**Comment by jneubert** [comment]
Browser: Firefox 33.0.2

**Comment by LaurensRietveld** [comment]
this should be fix now (your example is working again as well)
