### ISSUE TITLE
Suggestion: Sub-grouping option for tables

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#17]
Tabular SPARQL results often flatten 1:n structures in a way which hides the structure from the user instead of exposing it. See for example:

http://zbw.eu/beta/sparql-lab/?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/stw/added_by_category.rq

SQL reporting tools normally offer an option to impose some sub-grouping, using the values of a certain column as a sub-heading. I don't think that would be appropriate for SPARQL results. However, some grouping would be nice ...

I could think of an option like `groupByFirstColumn`. It could insert a fine line _before_ each row when value in the first column differs from the previous row. Another possible implementation, which I saw - and liked - in a ancient database system, was a formatting option which suppressed the output of the repeated value/cell completely. This could be adapted perhaps by fading such a cell, just to imply some optical rythm which makes the contents of the table easier to comprehend.

I have no idea how difficult it would be to implement such a function in or on top of YASR. Some things like paging through results backwards or dealing with results filtered by some string might be prohibitively unpleasant - but I didn't want to retain the idea.

Cheers, Joachim

**Comment by LaurensRietveld** [comment]
This is something which we have in the old yasgui version (the group-by option), and I'd like to have this included in YASR as well.
Its part of a bigger issue though: DataTables does not support this out-of-the-box, and a plugin which does, is untouched for the previous two years..  I'd like to get rid of DataTables anyway (don't like the API at all), and would like to switch to an alternative which supports features such as this with more ease (and, e.g. resizing of columns by the user as well).
Problem is: there is no good alternative. Dynatable is relatively actively developed, but a bit incompatible with the YASR license. SlickGrid seems like an option as well, but this one has not been modified for a year as well. 

I'll push changing DataTables as an issue, and we'll just have to wait until someone comes up with a proper alternative: https://github.com/YASGUI/YASR/issues/18

**Comment by LaurensRietveld** [comment]
@jneubert : I think the new pivot plugin supports what you want. In that case, we can close this ticket ;)

**Comment by jneubert** [comment]
This pivot table plugin sounds really exiting!I have to play a bit to understand it more fully.

**Comment by jneubert** [comment]
Phantastic - I think that offers much more than I had in mind.
