### ISSUE TITLE
Optimize column width

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#21]
Currently, columns could make better use of screen real estate:

1) White space between columns is relatively wide
2) Adaption of column width to the overall width of the browser viewport, in my opinion, is too limited

![2](https://cloud.githubusercontent.com/assets/2128921/5186998/51db3028-74ca-11e4-8142-beaa42d33920.PNG)

When the "mergeLabelsWithUris" option is used, things gets worse:

![1](https://cloud.githubusercontent.com/assets/2128921/5186852/61aa4e54-74c9-11e4-90f3-92777704aae9.PNG)

Defaults in this area are always disputable. It would be nice however to have an option for a more "squeezed" display.

**Comment by LaurensRietveld** [comment]
I won't like touching the default datatables configuration: different use
cases might have different preferences.
But you should be able to modify this easily using the datatables plugin
configuration. To modify these settings for YASR, you should edit this
object: YASR.plugins.table.defaults.datatable (see e.g. the datatables auto
width option (enabled by default):
http://datatables.net/reference/option/autoWidth)

**Comment by jneubert** [comment]
Thanks for the hint - I'll start some experiments.

**Comment by LaurensRietveld** [comment]
A change related to this is #36, where the use can now re-size columns. Not an exact fix though (resizing the table as a whole is not supported), but it might get you a bit further
