### ISSUE TITLE
Support question: How to set the default for page length?

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#22]
I tried 

```
YASR.plugins.table.defaults.datatable.pageLength = 50;
```

and a view variations, but obviously didn't hit the right spot.

**Comment by LaurensRietveld** [comment]
Hi Joachim

Ah, you just hit the wrong setting here ;). This particular option was not properly copied from the defaults objects.
This is now fixed.

gr Laurens

ps. When testing, make sure you don't run into caching problems here (whenever changing the page length via the drop-down, the value is stored in local storage for persistency reasons). To remove the cache, go to your website, then to the browser console (I assume you use chrome here), resources, 'LocalStorage', your domain, and delete the value starting with 'tableLength'.
