### ISSUE TITLE
Formatting gone after update to 2.2.4

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#23]
After updating from YASR 2.2.2 [example page](http://zbw.eu/beta/sparql-lab/index.html?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/added_concepts.rq) to 2.2.4 [same example page](http://zbw.eu/beta/sparql-lab/test1.html?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/added_concepts.rq), it looks like the formatting isn't applied any more (no spacing between columns, no formatting of buttons etc.
Firebug shows me as yasr/2.2.4/yasr.min.css only

```
.yasr {
    color: #333;
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 14px;
    line-height: 1.42857;
    margin-top: 5px;
}
```

My Firefox version is 33.1.1

**Comment by LaurensRietveld** [comment]
Hi Joachim.
As usual, thanks for letting me know ;)
This was an issue with the minified version (the regular worked as usual). The next version contains this fix (I'm making some more changes to the current version, so it'll probably be available this evening or tomorrow)
gr Laurens
