### ISSUE TITLE
mergeLabelsWithUris seems to not yet work with pivot tables

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#29]

**Comment by LaurensRietveld** [comment]
should be fixed now

**Comment by jneubert** [comment]
Hmm - works, kind off (only the URI fields are offered for selection, and their labels are displayed), yet they don't function as links.

**Comment by jneubert** [comment]
BTW - perhaps it could be useful to re-open an issue. Yet I see no button for this.

**Comment by LaurensRietveld** [comment]
Ah, think that button is only for me ;). But I'll leave it closed, as this is not possible at the moment. The plugin I use (pivottables) does not support drawing html in the columns yet (see https://github.com/nicolaskruchten/pivottable/pull/214)

**Comment by jneubert** [comment]
ok, I see.
