### ISSUE TITLE
Make search field optional

### ISSUE THREAD

**Issue by tploeger** [Triply-Dev/YASGUI.YASR-deprecated#3]
It would be great if you can disable the search bar, just like you can disable the download button and result visualization selector.

**Comment by LaurensRietveld** [comment]
This is already possible by changing the plugin settings (see datatables reference).
If you (before initialization) you add this, the length-change widget and filter functionality should be gone:
    YASR.plugins.table.defaults.datatable.searching = false;
    YASR.plugins.table.defaults.datatable.lengthChange = false;

**Comment by tploeger** [comment]
:+1:
