### ISSUE TITLE
Add pivot export functionality

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASR-deprecated#30]
Button should only be enabled for tables. Can use the csv export functionality of YASR, but need to do some tricks to resolve col and row spans. Preferably, wait and see whether this feature becomes available as part of pivottable (see PR https://github.com/nicolaskruchten/pivottable/pull/187)

**Comment by nicolaskruchten** [comment]
Check out http://nicolas.kruchten.com/pivottable/examples/mps_export.html :)

**Comment by LaurensRietveld** [comment]
@nicolaskruchten : Excellent, good to see! For consistency reasons, I'll probably modify some of your code in order to use it similarly as how current visualizations in YASR are exported.

**Comment by nicolaskruchten** [comment]
Cool. Please don't hesitate to pull-request back if you come up with a more consistent way to export... I had to make some editorial decisions...

**Comment by LaurensRietveld** [comment]
@nicolaskruchten : I've recently added my take on the pivot export functionality. To see it in action: go to yasr.yasgui.org, execute the query below (by pressing the play button in the query window), and select the pivot output.
The download button either downloads an svg images when a google chart is selected, or downloads a csv for a regular table rendering. For the CSV downloads, I've opted for simply duplicating cells in the case of row and col spans. Not the most ideal solution, but I doubt there is any..
Not sure whether this is an approach you'd like to see in the pivot table plugin as well, but at least you can get to see it working in action ;)

a test query:
`SELECT DISTINCT ?type ?person WHERE {
  ?person a ?type .
}
LIMIT 10`
