### ISSUE TITLE
Suggestion: Make columns moveable and collapsable

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#38]
Hi Laurens,

It's a very low priority thing - but perhaps it would be just a small extension to enable pushing columns around or removing them completely from display.

Of course, this can be done easyly by tweaking the select clause and re-executing the query. In my use case - predefined queries hidden from the unsophisticated user - it would be nice, however. Particularly because I sometimes want to include columns which are necessary for pivoting, but not very meaningful for the human user (see, e.g., the first column in [this report](http://zbw.eu/beta/sparql-lab/stw.html?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/stw/deprecated_concepts_by_category.rq&language=en&oldVersion=8.12&newVersion=8.14&hide=1)).

Cheers, Joachim

**Comment by wouterbeek** [comment]
I understand the use case, but it seems to be something that few users will use; at the same time this will complicate the UI a little bit for all users (my 2 cents).

@jneubert How easy/difficult is it to implement a custom client based on the current YASR and YASQE components where you would implement features like these?

**Comment by jneubert** [comment]
Hi Wouter, 

as said above, this is very low priority thing, so I have not considered to implement it myself. It would be nice to have, if implemented in some upstream library, but really isn't worth much implementation effort. So I close the issue here.

Cheers, Joachim
