### ISSUE TITLE
Downloading of CSV not working in firefox

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASR-deprecated#39]
Posted this by accident as a YASQE issue (https://github.com/YASGUI/YASQE/issues/45)

**Comment by LaurensRietveld** [comment]
And post by Joachim: Maybe somehow related: With YASR 2.4.1, I'm not able to download SVG graphics (the button stays grey), in Chrome as well as in FF.

**Comment by LaurensRietveld** [comment]
I've fixed the firefox issue. Joachim: I can't reproduce the SVG feature though (works well for both firefox and chrome)
What kind of visualization did you try to download?

**Comment by jneubert** [comment]
Hi Laurens, I can reproduce the SVG issue with the latest libraries. What happens is that the download button is greyed out when I switch to Pivot Table. What I actually want to download is the treemap.

As this happens in Chrome too, I supposed that it's an issue of my script ([here](https://github.com/jneubert/sparql-gui-gh/blob/master/sparql-lab.js), but changing a few things (persitency prefix, useGoogleCharts) didn't help.

**Comment by LaurensRietveld** [comment]
Ah, the  problem is that a tree map is not an svg. D3 simply draws it as a set of divs, making it tricky to export to file

**Comment by jneubert** [comment]
Ahhrrg - I hoped that just the treemaps would work and give me nice scalable images. Bad luck ...
