### ISSUE TITLE
remove d3 from npm dependencies

### ISSUE THREAD

**Issue by aindlq** [Triply-Dev/YASGUI.YASR-deprecated#40]
Hi. I was not able to find where YASR uses d3 library, if it is not in use right now it would be great to remove it from dependencies, because it transitively depends on contextify and it can be problematic to install it on some platforms.

**Comment by LaurensRietveld** [comment]
Hi Artem, it is one of the visualizations (the tree map) of the pivottable plugin. I wasn't familiar with these installation problems. Are you talking about this one? http://stackoverflow.com/questions/27410558/installing-d3-using-npm-causes-contextify-errors

**Comment by aindlq** [comment]
Not really... What do you think about modular YASR. Top level project which defines API and some common functionality for components. And plugins/visualizations, each as separate artifact.

So for example it would be not required to use datatables or google chart with YASR. And it would be up to the developer to chose which plugins should be included.

If you like this idea, I think I can help to do this.

**Comment by LaurensRietveld** [comment]
A large part of such a modular approach is already in place:
Via the YASR settings you should be able to disable and enable different visualizations (http://yasr.yasgui.org/doc/#config).
This should be used in combination with using the regular yasr library (not the bundled one), to avoid loading the corresponding dependencies (see this gist: http://bl.ocks.org/LaurensRietveld/b76a617c128f485ef0f3)

I agree that it is not the nicest modular approach. Rationale behind this particular setup is mostly that some plugins share dependencies. I.e., bundling each plugin would needlessly increase the total lib size

But, any help/feedback is appreciated!
