### ISSUE TITLE
"Too much recursion" when persistency is disabled

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#53]
When I set

```
YASR.defaults.persistency.prefix = false;
```

I get a "Too much recursion" error. This can be reproduces with an an [adapted version of glue.js](http://zbw.eu/beta/sparql-lab/glue.js) of your gist, and yasr 2.4.11. Unfortunately I don't know at which version it started to occur.

**Comment by LaurensRietveld** [comment]
This bug was caused by #43, and fixed in the version I published a few seconds ago. Again, thanks for the report!
