### ISSUE TITLE
Persistency forever?

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#54]
Since yesterday, I encounter strange effects: The queries loaded from Github reflect an prior state of the query. Sometimes completely different queries are executed. 

I had similar issues in the past, and therefore disabled persistency. Did the solution of #53 bring it back, perhaps?

**Comment by LaurensRietveld** [comment]
Do you have a demo where this goes wrong? Haven't experienced something like this before though.

I took a look at your deployment (http://zbw.eu/beta/sparql-lab/sparql-lab.js), and I did see one strange thing: the `consumeUrl` function at one point declares a variable `var query = ...`, and assigns some values to that variable. But that variable is never passed on to yasqe (e.g. using `yasqe.setValue(query)`)
Is this related to your problem?

**Comment by jneubert** [comment]
Completely my fault - I deleted the wrong line in the script ...

Thanks for the hint - Joachim
