### ISSUE TITLE
Injecting a value for filtering results

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#55]
I'd like to set an initial search/filter string for yasr programmatically.

My use case is that I want to drill down from a chart (like [that one](http://zbw.eu/beta/stw_deltas/v/changed_descriptors.en.html)) to the [result of a sparql query](http://zbw.eu/beta/sparql-lab/stw.html?queryRef=https://api.github.com/repos/jneubert/skos-history/contents/sparql/stw/added_concepts_by_category.rq&language=en&oldVersion=8.12&newVersion=8.14&hide=1), filtered by the category string.

Perhaps that Is possible with the current yasr implementation, but I couldn't figure out how.

**Comment by jneubert** [comment]
Hi Laurens, I'm currently preparing an drill-down application which will have a hundred entry points into a pre-calculated and saved SPARQL result set (= a hundred possible filter conditions, times 8 or 10 different queries, times two languages - so I don't want to pre-calculate and save all the chunks).

I've poked arround quite a bit, but had no success so far in injecting a filter value. In particular, I couldn't get a grip on the DataTable object, which for sure is somewhere deep down in yasr. If I could do something like

```
$("#DataTables_Table_0").dataTable({
  "fnInitComplete": function(oSettings, json) {
    $("#" + oSettings.sTableId+"_filter input").val(getParameterByName('search'));
```
- perhaps that already could do the trick.

**Comment by LaurensRietveld** [comment]
apologies for the delay! 
I think you are looking for this method:
`$('.dataTables_filter input').val('aaaaaaaaa').change()`

This looks for the text input, adds a value, and trigger the 'change' event (which makes the datatable update). This avoids using the actual datatables object altogether. Just make sure to call this after initializing YASR.

Was this what you are looking for.

**Comment by jneubert** [comment]
Thank you very much for the hint. This looks beautifully simple. It rightly puts the value into the search box, but does not execute the search.

When I put the command into the Javascript console in Firefox or Chrome directly, the change is not recognized (or acted upon) neither.

**Comment by LaurensRietveld** [comment]
Do you have an example link I can try out?

**Comment by jneubert** [comment]
Here is a preview: http://zbw.eu/beta/tmp2/relaunch/view_change_report.en.html?report=added_descriptors_by_category.en&search=V.05&heading1=Added%20descriptors%20%20%28v%208.06%20-%20v%209.0%29

**Comment by LaurensRietveld** [comment]
Ah, my suggestion was slightly off. Instead of 'change', you should trigger the 'keyup' event. And, because the event is bound using the YASR jquery (and not the one exposed in the window object), you should use that jquery instead. I.e., the following should work:
`YASR.$('.dataTables_filter input').val('some filter value').keyup()`

**Comment by jneubert** [comment]
This works perfectly - thank you so much!!

**Comment by LaurensRietveld** [comment]
great, good to hear!
