### ISSUE TITLE
Option to disable Pivot tab

### ISSUE THREAD

**Issue by stain** [Triply-Dev/YASGUI.YASR-deprecated#56]
Hi, is it possible to have an option to disble the pivot table? Similar to the google chart option.

https://github.com/YASGUI/YASR/blob/gh-pages/src/main.js#L56

I love the pivot function - but some users get confused and don't know what to do with it - for many query results the Pivot Tables are not really easy to use.

**Comment by stain** [comment]
I assume I can just remove the `pivot.js`dependency - but that's tricky to do programmatically on a case-by-case basis.

**Comment by LaurensRietveld** [comment]
Removing the dependency would work, but removing 'pivot' from the 'outputPlugins' option should work as well (see http://yasr.yasgui.org/doc/#config). 
Any luck with that?

**Comment by stain** [comment]
Thanks, that is a good way to do it. Apologies for missing this in the
documentation!

**Comment by LaurensRietveld** [comment]
no problem ;)
