### ISSUE TITLE
Links w/o target="_blank"?

### ISSUE THREAD

**Issue by jneubert** [Triply-Dev/YASGUI.YASR-deprecated#64]
Links on the YASR results page using `mergeLabelsWithUris` are created with `target="_blank"`. In some scenarios, it could be useful to have the link target in the same tab, in order to provide a seamless "back button" navigation.

Can the link target be triggered somehow?

Cheers, Joachim

**Comment by wouterbeek** [comment]
IIUC then the question is whether the default URI target can become a configuration option.

**Comment by LaurensRietveld** [comment]
I'm up for setting a default URI target (don't want to set this only for one kind of link).
