### ISSUE TITLE
Make handling of URI labels more consistent

### ISSUE THREAD

**Issue by LaurensRietveld** [Triply-Dev/YASGUI.YASR-deprecated#67]
How labels are handled right now: 
- By default, try fetching label as title from preflabel.org
- Optionally, for the table and pivottable plugin, use the 'mergeLabelsWithUris' option (see http://yasr.yasgui.org/doc/) to merge bindings in the SPARQL resultset together (label with be text, URI will be href value)
- Another option (presented here https://github.com/YASGUI/YASQE/issues/61) is to fetch the labels by dereferencing the URI

These options are now configurable per output plugin. To make these options more manageable, we should make the following improvements:
- Add these option to the main YASR options object, instead of each plugin independently (and, if users want to change behaviour for one particular output plugin, they can overwrite it for that particular one)
- Make the options more genereric, i.e. ideally:

``` js
YASR.defaults.options.labels {
    source: [preflabel | labelBinding | dereferenceableUri],
    asText: [true|false]//display label as text instead of the URI, or display label as part of the title tag
```

One catch: async options (preflabel and dereferenceable URIs) won't work for all plugins, e.g. the google charts

This change would probably not be fully backwards compatible, so we'd need to up the major semversion of YASR for this one

**Comment by jneubert** [comment]
Would that mean that I'd have to choose one mechanism? I'd suppose that oftenly some labels can be obtained from the query, while others may require external lookup. The naming convention for mergeLabelsWithURIs is very nice in this regard, because it gives the query author control on column level. But I have no good idea how this could be achieved for different lookup options ...

**Comment by wouterbeek** [comment]
@LaurensRietveld Would it be possible to turn this into a configuration option that is a list of functions?  The functions would all try to replace IRIs with labels in the result set.  When functions earlier in the list fail, functions later in the list are tried.  Users could add custom functions.  The following standard functions could be offered:

  1. SPARQL query to the same endpoint.  This would even allow you to match on a language tag.
  2. prefLabel.org lookup
  3. IRI dereference
  4. Take a local name postfix from the IRI (after the last `#` or after the last `/`)

I'm a bit mixed WRT functions (2) and (3) BTW.  Their coverage seems to be rather limited.

**Comment by LaurensRietveld** [comment]
I agree about the coverage of preflabel and dereferencing. Another thing with dereferencing is that we won't always be able to access the URL due to CORS issues.

In general, I'm not in favor of having this many fallbacks. If you've got 100 distinct literals you'd like to show, it would issue (in the worst case) up to 300 http requests for single view. You could of course optimize this to keep the number down, but it would still be way too much.

Tbh I'm inclined to remove the dependency on preflabel, and simply take the local postfix. Thoughts?

**Comment by wouterbeek** [comment]
+1 for the local postfix

Longterm somebody™ will create a comprehensive lookup service that can translate 100+ entities instantly against a RocksDB backend in 1 HTTP request.

**Comment by jneubert** [comment]
So, we would have three (or four?) ways of displaying URIs:

1) label from some other column of the query result (mergeLabelsWithURIs)
2) postfix as link (per config)
3) full URI as link (should be possible, too)
4) local lookup (?? - but: could be also part of the query, and has to be, if e.g. different graphs are involved)

Right?

**Comment by LaurensRietveld** [comment]
I'm inclined to go for two options:

1. Display localname (postfix) of IRIs and the full IRI in the same field. Postfix will have the most prominent visibility, where the full IRI is displayed with less emphasis (e.g. smaller font size). This covers your 2 and 3
2. A custom 'renderField' function that you can add to your config, so that publishers can decide on how they want to render the field. This covers your 1 and 4. This would mean that `mergeLabelsWithURIs` would be removed. I'll post a snippet on how to set the renderField function to get the same behaviour

Having just these two options would reduce the dependencies of YASR, make the range of configuration options smaller, and increase the rendering flexibiliy

**Comment by LaurensRietveld** [comment]
This feature was dropped in the latest release (https://github.com/TriplyDB/Yasgui)
Still, a useful discussion. When we want to make things more human readable again in the new repo, we should revisit this issue
