### ISSUE TITLE
Suggestion: Have count of results at top v. bottom

### ISSUE THREAD

**Issue by alanruttenberg** [Triply-Dev/YASGUI.YASR-deprecated#70]
If you select a large number of results to show you might have to scroll for a while to find the count. Easier if it is on top.

**Comment by LaurensRietveld** [comment]
I've updated the interface a bit. A pitty that we need another row for this information (as there wasnt space left to the right of the YASR output buttons), but I see the use of having this information at the top of YASR as well.

**Comment by alanruttenberg** [comment]
What if the output buttons were offered as a popup instead?

**Comment by LaurensRietveld** [comment]
Would be an option, but we'd still need a button to trigger expanding the output buttons. But I'm with the solution so far
