### ISSUE TITLE
Missing require('jquery-ui/sortable') in main.js?

### ISSUE THREAD

**Issue by alanruttenberg** [Triply-Dev/YASGUI.YASR-deprecated#71]
I was getting an error on table redraw when (trying) to run from the repo. That fixed it. Stumbling around I also updated to Datatables to latest, which fixed an earlier problem. 

Is it possible that some other things are not checked in? If so I would be grateful if they could be.

Thanks,
Alan

**Comment by LaurensRietveld** [comment]
I cannot reproduce this issue. I cloned a fresh version of YASR, ran `npm install`, and `gulp serve`. 
Where did you get the error? During packaging, or when running YASR?

**Comment by alanruttenberg** [comment]
When running YASGUI, when query came back, but before display. Raw worked fine. But I think I got confused. It was YASGUI that needs the ui-sortable, for tabs.  Before that problem I was getting an error about using "in" in some situation.

I wanted to live edit YASGUI as a whole, which means changes in YASR,YASQE would also trigger rebuild.  

I used npm link to point yasgui-yasr to YASR repo and likewise for YASQE, and then had YASGUI also watch for changes to the dist.

So this seems to work now - I don't start servers but do start livereload on YASR and YASQE , then serve on YASGUI. Then editing anywhere (but Utils) is live.

Is there an easier way? (bit of a steep learning curve to get to this point)

**Comment by LaurensRietveld** [comment]
> Is there an easier way? (bit of a steep learning curve to get to this point)
> That sounds exactly as how I would have done it. (though I develop YASR and YASQE separately, and not from the YASGUI interface)
> And jup, its a tricky learning curve. The most tricky thing was getting browserify to play nice with several libraries I included.
