### ISSUE TITLE
Export to CSV column mix up

### ISSUE THREAD

**Issue by jjkoehorst** [Triply-Dev/YASGUI.YASR-deprecated#80]
When creating a matrix and download this as a CSV file, variables are getting mixed up. See figure how it should be.

![schermafbeelding 2015-08-21 om 13 14 47](https://cloud.githubusercontent.com/assets/4471699/9407112/b08fd802-4806-11e5-814a-b25ce3a8d54c.png)

Yet it creates something in the shape of (have removed half of the line as it otherwise gets too big

What should be noted is that you suddenly see featureType popping up twice as ssb:tRNA ssb:tRNA. Which should not be. In the next row this variable is completely absent and all columns are shifted to the left mixing everything.

  ,  ,  ,  , "label" , "EXP1",
 "sha384" , "begin" , "end" , "featureType" ,  ,  ,  ,  ,
 "1a63e644f3bfc0330d0dcb8094c1fe40f064e1573d159ffcdcae3a742bd56ac508bce7ecd9f56fdf5e41628916d4a641" , "1937" , "1937" , "ssb:tRNA" , "ssb:tRNA" , "12,372.00"
 "1a63e644f3bfc0330d0dcb8094c1fe40f064e1573d159ffcdcae3a742bd56ac508bce7ecd9f56fdf5e41628916d4a641" , "2777" , "1937" , "22,814.00" , "5,824.00" , "31,106.00"
 "1a63e644f3bfc0330d0dcb8094c1fe40f064e1573d159ffcdcae3a742bd56ac508bce7ecd9f56fdf5e41628916d4a641" , "2777" , "1937" , "25,091.00" , "103.00" , "40.00" , "51.00"

**Comment by LaurensRietveld** [comment]
Thanks for the report. Do you have a query + endpoint example I can work with?

A note about ssb:tRNA popping up twice: there is no pretty solution for this, because CSV does not support col spans.

**Comment by jjkoehorst** [comment]
Ill set up one now

**Comment by jjkoehorst** [comment]
I have contacted you hopefully on the right email address with further information.

**Comment by LaurensRietveld** [comment]
The issue should now be fixed, and integrated in the latest YASGUI version as well. Could you check it out?
