### ISSUE TITLE
Display not quoting HTML content.

### ISSUE THREAD

**Issue by afs** [Triply-Dev/YASGUI.YASR-deprecated#83]
This was reported in https://issues.apache.org/jira/browse/JENA-1123

Displaying, say, the string "<b>bold</b>" causes **bold** text (and no <b>...</b>).

It also allows "<script>...."

"<" and ">" need quoting

**Comment by LaurensRietveld** [comment]
ah, that's a silly bug. I'll fix it together with some other issues in the next few days

**Comment by afs** [comment]
Edited report - seems like github does not quote &lt; or &gt; either!! This text used "`& l t ;`"

**Comment by LaurensRietveld** [comment]
Aah, I found the issue. This isn't a problem in YASR itself (http://yasr.yasgui.org works fine with the given query), but a bit in the modifications we made while integrating YASQE and YASR in jena. 
Specifically, what needs to change is the `YASR.plugins.table.defaults.getCellContent` function in the `qonsole.js` file. Here, the values that are stored in dom elements need to be escaped.

In YASR I use the following regex: `return unescaped.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');`

I can make a pull request in jena if needed (preference for a certain branch?), or of course feel free to modify this yourself

**Comment by afs** [comment]
That's good news.

A PR to Jena master would be perfect.

**Comment by LaurensRietveld** [comment]
I've added a PR to the jena github, so we can continue any further issues there if needed: https://github.com/apache/jena/pull/125

**Comment by afs** [comment]
Thank you!
