### ISSUE TITLE
Add support for MultiPolygon in Geo view

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#89]
WKT literals of type `MultiPolygon` are currently not supported.  A multi-polygon is a list of polygons (which are already supported).  While you're at it, you may also add support for (the less common) `MultiPoint` and `MultiLine` types.  They are also simply lists of points and lines, respectively.

**Comment by LaurensRietveld** [comment]
This seems to be supported already: http://yasgui.org/short/HyxQSaDsx
