### ISSUE TITLE
String values changed into URLs. Bug?

### ISSUE THREAD

**Issue by p1d1d1** [Triply-Dev/YASGUI.YASR-deprecated#90]
Is this a "nice" bug?
Go here: http://yasgui.org/#query=PREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX+gn%3A+%3Chttp%3A%2F%2Fwww.geonames.org%2Fontology%23%3E%0Aselect+%3FMunicipality+%3FName+%3FPopulation%0Awhere%0A%7B%0A%3FMunicipality+a+gn%3AA.ADM3+.%0A%3FMunicipality+schema%3Aname+%3FName+.%0A%3FMunicipality+gn%3Apopulation+%3FPopulation+.%0A%3FMunicipality+%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2Fissued%3E+%3FDate+.%0AFILTER+(%3FDate+%3D+%222016-01-01%22%5E%5Exsd%3Adate)%0A%7D%0AORDER+BY+DESC(%3FPopulation)%0ALIMIT+5&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Fsparql.geo.admin.ch%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&outputFormat=table

Change to Google Chart then change back to table --> The values under Name are transformed in URLs.

**Comment by LaurensRietveld** [comment]
Well, it's certainly an original one. I'll take a look
