### ISSUE TITLE
Add support for 3D points

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#91]
The idea is to _parse_ 3D points, but to _display_ them as 2D points on the Leaflet map.  (3D maps are still quite resource-intensive and/or require complicated libraries to work on most browsers.)

Example of a query with a 3D point:

```sparql
prefix  geo: <http://www.opengis.net/ont/geosparql#>
select * {
  bind ("Point z (6.2 52.0 1.0)"^^geo:wktLiteral as ?o)
}
```

WKT allows the third coordinate in points to either represent a point's position on the Z-axis or for linear referencing (not commonly used in Linked Data AFAICT).  The syntax for WKT points is as follows:

```bnf
<point> ::= <x> <y> [ <z> ] [ <m> ] 
<x> ::= <number> 
<y> ::= <number>
<z> ::= <number>
<m> ::= <number>
```

The interpretation of the third coordinate is given after the shape name and before the list of coordinates, as follows (the `z` character in the above example):

```bnf
<z m> ::= ZM | Z | M
```

**Comment by LaurensRietveld** [comment]
Would be cool to support this. I'd like to wait for wicket (the lib we use for parsing wkt) to support this: https://github.com/arthur-e/Wicket/issues/42
