### ISSUE TITLE
Small tweaks to RDF aliases to be more in line with GeoSPARQL usage

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#92]
For compliance with GeoSPARQL:

  1. Alias `geo` should abbreviate IRI prefix `http://www.opengis.net/ont/geosparql#`.  This currently abbreviates IRI prefix `http://www.w3.org/2003/01/geo/wgs84_pos#`, but this could be abbreviated by alias `wgs84` instead.
  2. Alias `geor` should be defined to abbreviate IRI prefix `http://www.opengis.net/def/rule/geosparql/`

**Comment by LaurensRietveld** [comment]
the `geor` prefix is now in prefix.cc (and as autocompletion suggestion in YASQE)
I'll upvote the `geo` GIS prefix a few times in prefix.cc to see whether we can push that a bit higher

**Comment by wouterbeek** [comment]
We finally made it!  The GeoSPARQL prefix has been at the top of this list for a few weeks now (http://prefix.cc/geo), toppling the WGS84 long/lat vocabulary.

These prefixes are also in YASQE now.  Closing...
