### ISSUE TITLE
Add support for GML

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#93]
GeoSPARQL defines two serialization profiles: WKT and GML.  If there is a JavaScript-based GML parser, then it would be nice to also support the parsing of GML literals.  The parser should be able to parse GML snippets (not full documents) that describe exactly one instance of UML class `GM_Object` / XML element `gml:AbstractGeometry`.

A simple example of the same point in GML and WKT serialization:

```xml
?geometry geo:hasGML "<gml:Point><gml:coordinates>1.1, 2.2</gml:coordinates></gml:Point>"^^geo:gmlLiteral ;
          geo:hasWKT "Point (1.1 2.2)"^^geo:wktLiteral .
```

**Comment by LaurensRietveld** [comment]
Just for my frame of reference: how would GML in a SPARQL result look like?

**Comment by wouterbeek** [comment]
I've found the XML Schema definition for the GML geometry types.  We now need to find a JavaScript library that parses an XML input string into a DOM object based on a supplied schema definition.
