### ISSUE TITLE
Improved way of displaying very long literals

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#94]
This use case comes up very regularly in geodata, where lengthy WKT strings abound: when scrolling throw the result set rows it seems as if a literal contains two WKT strings (see screenshot).  Actually, the second WKT string belongs to the next row (currently out of view).

@LaurensRietveld mentioned CSS-based newlines as a good solution for this: copy/pasting the content would still work (because of the neat separation between DOM/content and display/CSS).

![yasr](https://cloud.githubusercontent.com/assets/1685012/23962142/77e3323c-09ad-11e7-8cf9-d454a9ffd02f.png)

**Comment by LaurensRietveld** [comment]
Now I see the screenshot I'm a bit confused. It seems the WKT string is already split accros lines. But if I understand your problem description, its exactly the splitting accros lines (combined with vertical center alignment) thats a problem here.

**Comment by LaurensRietveld** [comment]
Would you expect top-vertical-alginment here? (that wouldnt look that great btw if there are less lengthy results)

**Comment by jneubert** [comment]
Well, perhaps an option to trigger top-vertical-alginment? Would help with some of my queries, too.

**Comment by wouterbeek** [comment]
@jneubert Thanks for the suggestion.

The `vertical-align` CSS property "specifies the vertical alignment of an inline or table-cell box" (MDN).

The value `top` means: "Align the top of the element and its descendants with the top of the entire line" (MDN).

**Comment by LaurensRietveld** [comment]
I've decided to fix this in a different way. The problem was that it was difficult to distinguish between rows, so I added a different row bg color for even/uneven rows
