### ISSUE TITLE
Support autocomplete for GeoSPARQL classes, functions and properties

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#95]
Classes:
  - `geo:Feature`
  - `geo:Geometry`
  - `geo:SpatialObject`

Datatype IRIs:
  - `geo:gmlLiteral`
  - `geo:hasGeometry`
  - `geo:wktLiteral`

Functions:
  - `geo:ehEquals`
  - `geo:ehDisjoint`
  - `geo:ehMeet`
  - `geo:ehOverlap`
  - `geo:ehCovers`
  - `geo:ehCoveredBy`
  - `geo:ehInside`
  - `geo:ehContains`
  - `geo:ehContains`
  - `geo:rcc8eq`
  - `geo:rcc8dc`
  - `geo:rcc8ec`
  - `geo:rcc8po`
  - `geo:rcc8tppi`
  - `geo:rcc8tpp`
  - `geo:rcc8ntpp`
  - `geo:rcc8ntppi`
  - `geo:sfEquals`
  - `geo:sfDisjoint`
  - `geo:sfIntersects`
  - `geo:sfTouches`
  - `geo:sfWithin`
  - `geo:sfContains`
  - `geo:sfOverlaps`
  - `geo:sfCrosses`
  - `geof:boundary`
  - `geof:buffer`
  - `geof:convexHull`
  - `geof:difference`
  - `geof:distance`
  - `geof:envelope`
  - `geof:getSRID`
  - `geof:intersection`
  - `geof:relate`
  - `geof:symDifference`
  - `geof:union`

Namespaces:
  - `geo`: http://www.opengis.net/ont/geosparql#
  - `geof`: http://www.opengis.net/def/function/geosparql/
  - `geor`: http://www.opengis.net/def/rule/geosparql/
  - `gml`: http://www.opengis.net/ont/gml#
  - `ogc`: http://www.opengis.net/
  - `sf`: http://www.opengis.net/ont/sf#

Properties:
  - `geo:coordinateDimension`
  - `geo:dimension`
  - `geo:hasDefaultGeometry`
  - `geo:hasGML`
  - `geo:hasSerialization`
  - `geo:hasWKT`
  - `geo:isEmpty`
  - `geo:isSimple`
  - `geo:spatialDimension`

**Comment by LaurensRietveld** [comment]
Most are already in LOV (and thus available for autocompletion in YASQE). Others I added.
