### ISSUE TITLE
Incorrect handling of TSV result set format

### ISSUE THREAD

**Issue by wouterbeek** [Triply-Dev/YASGUI.YASR-deprecated#96]
For the TSV result set format the following expressions are handled incorrectly:
  - Variable names are not parsed correctly.  Specifically, the first character (i.e., `?`) should be skipped.
  - IRI terms are not parsed correctly.  Specifically, the first (i.e., `<`) and last (i.e., `>`) characters should be skipped.

Example of a TSV result set serialization:

```text/tab-separated-values
?s	?p	?o
<http://localhost/misc/UnknownDocument>	<http://www.w3.org/1999/02/22-rdf-syntax-ns#type>	<http://xmlns.com/foaf/0.1/Document>
```

**Comment by LaurensRietveld** [comment]
hmm, YASR doesnt support TSV. Did you request TSV by setting the accept header? In that case, it's the SPARQL endpoint that screws this up ;)

**Comment by LaurensRietveld** [comment]
aahh, misunderstood, thought this was about exporting to TSV (which we don't support). Instead, it's about parsing TSV responses from endpoints.
